---
title: "p8105_hw6_rr3423.Rmd"
author: "Ragyie Rawal"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## PROBLEM 1 

### Loading and cleaning data for regression analysis 

```{r import_data}
birthweight_data = read_csv("data/birthweight.csv")
```

```{r tidy_data}
birthweight_df = 
  birthweight_data %>% 
  janitor::clean_names() %>% 
  mutate(
    babysex = case_when(babysex == "1" ~ "male",
                        babysex == "2" ~ "female"),
    frace = case_when(frace == "1" ~ "White",
                      frace == "2" ~ "Black",
                      frace == "3" ~ "Asian",
                      frace == "4" ~ "Puerto Rican", 
                      frace == "8" ~ "Other",
                      frace == "9" ~ "Unknown"),
    malform = case_when(malform == "0" ~ "absent",
                        malform == "1" ~ "present"),
    mrace = case_when(mrace == "1" ~ "White",
                      mrace == "2" ~ "Black",
                      mrace == "3" ~ "Asian",
                      mrace == "4" ~ "Puerto Rican",
                      mrace == "8" ~ "Other")
  )
```

Checking for missing data by identifying any NA values in columns 

```{r check_NA}
birthweight_df %>% 
  summarise(across(everything(), ~ sum(is.na(.))))
```
There are no NA values, thus no missing data in the birthweight dataset.  
